/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as CapabilitiesRouteImport } from './routes/capabilities'
import { Route as ProjectIdRouteImport } from './routes/$projectId'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectIdIndexRouteImport } from './routes/$projectId.index'
import { Route as CapabilitiesCapabilityKeyRouteImport } from './routes/capabilities.$capabilityKey'
import { Route as ProjectIdMemoryIdRouteImport } from './routes/$projectId.$memoryId'

const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const CapabilitiesRoute = CapabilitiesRouteImport.update({
  id: '/capabilities',
  path: '/capabilities',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdRoute = ProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdIndexRoute = ProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectIdRoute,
} as any)
const CapabilitiesCapabilityKeyRoute =
  CapabilitiesCapabilityKeyRouteImport.update({
    id: '/$capabilityKey',
    path: '/$capabilityKey',
    getParentRoute: () => CapabilitiesRoute,
  } as any)
const ProjectIdMemoryIdRoute = ProjectIdMemoryIdRouteImport.update({
  id: '/$memoryId',
  path: '/$memoryId',
  getParentRoute: () => ProjectIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$projectId': typeof ProjectIdRouteWithChildren
  '/capabilities': typeof CapabilitiesRouteWithChildren
  '/review': typeof ReviewRoute
  '/$projectId/$memoryId': typeof ProjectIdMemoryIdRoute
  '/capabilities/$capabilityKey': typeof CapabilitiesCapabilityKeyRoute
  '/$projectId/': typeof ProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/capabilities': typeof CapabilitiesRouteWithChildren
  '/review': typeof ReviewRoute
  '/$projectId/$memoryId': typeof ProjectIdMemoryIdRoute
  '/capabilities/$capabilityKey': typeof CapabilitiesCapabilityKeyRoute
  '/$projectId': typeof ProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$projectId': typeof ProjectIdRouteWithChildren
  '/capabilities': typeof CapabilitiesRouteWithChildren
  '/review': typeof ReviewRoute
  '/$projectId/$memoryId': typeof ProjectIdMemoryIdRoute
  '/capabilities/$capabilityKey': typeof CapabilitiesCapabilityKeyRoute
  '/$projectId/': typeof ProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$projectId'
    | '/capabilities'
    | '/review'
    | '/$projectId/$memoryId'
    | '/capabilities/$capabilityKey'
    | '/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/capabilities'
    | '/review'
    | '/$projectId/$memoryId'
    | '/capabilities/$capabilityKey'
    | '/$projectId'
  id:
    | '__root__'
    | '/'
    | '/$projectId'
    | '/capabilities'
    | '/review'
    | '/$projectId/$memoryId'
    | '/capabilities/$capabilityKey'
    | '/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectIdRoute: typeof ProjectIdRouteWithChildren
  CapabilitiesRoute: typeof CapabilitiesRouteWithChildren
  ReviewRoute: typeof ReviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capabilities': {
      id: '/capabilities'
      path: '/capabilities'
      fullPath: '/capabilities'
      preLoaderRoute: typeof CapabilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId': {
      id: '/$projectId'
      path: '/$projectId'
      fullPath: '/$projectId'
      preLoaderRoute: typeof ProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/': {
      id: '/$projectId/'
      path: '/'
      fullPath: '/$projectId/'
      preLoaderRoute: typeof ProjectIdIndexRouteImport
      parentRoute: typeof ProjectIdRoute
    }
    '/capabilities/$capabilityKey': {
      id: '/capabilities/$capabilityKey'
      path: '/$capabilityKey'
      fullPath: '/capabilities/$capabilityKey'
      preLoaderRoute: typeof CapabilitiesCapabilityKeyRouteImport
      parentRoute: typeof CapabilitiesRoute
    }
    '/$projectId/$memoryId': {
      id: '/$projectId/$memoryId'
      path: '/$memoryId'
      fullPath: '/$projectId/$memoryId'
      preLoaderRoute: typeof ProjectIdMemoryIdRouteImport
      parentRoute: typeof ProjectIdRoute
    }
  }
}

interface ProjectIdRouteChildren {
  ProjectIdMemoryIdRoute: typeof ProjectIdMemoryIdRoute
  ProjectIdIndexRoute: typeof ProjectIdIndexRoute
}

const ProjectIdRouteChildren: ProjectIdRouteChildren = {
  ProjectIdMemoryIdRoute: ProjectIdMemoryIdRoute,
  ProjectIdIndexRoute: ProjectIdIndexRoute,
}

const ProjectIdRouteWithChildren = ProjectIdRoute._addFileChildren(
  ProjectIdRouteChildren,
)

interface CapabilitiesRouteChildren {
  CapabilitiesCapabilityKeyRoute: typeof CapabilitiesCapabilityKeyRoute
}

const CapabilitiesRouteChildren: CapabilitiesRouteChildren = {
  CapabilitiesCapabilityKeyRoute: CapabilitiesCapabilityKeyRoute,
}

const CapabilitiesRouteWithChildren = CapabilitiesRoute._addFileChildren(
  CapabilitiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectIdRoute: ProjectIdRouteWithChildren,
  CapabilitiesRoute: CapabilitiesRouteWithChildren,
  ReviewRoute: ReviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
