/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MemoriesRouteImport } from './routes/memories'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MemoriesIndexRouteImport } from './routes/memories.index'
import { Route as MemoriesIdRouteImport } from './routes/memories.$id'

const MemoriesRoute = MemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriesIndexRoute = MemoriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MemoriesRoute,
} as any)
const MemoriesIdRoute = MemoriesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MemoriesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/memories': typeof MemoriesRouteWithChildren
  '/memories/$id': typeof MemoriesIdRoute
  '/memories/': typeof MemoriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/memories/$id': typeof MemoriesIdRoute
  '/memories': typeof MemoriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/memories': typeof MemoriesRouteWithChildren
  '/memories/$id': typeof MemoriesIdRoute
  '/memories/': typeof MemoriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/memories' | '/memories/$id' | '/memories/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/memories/$id' | '/memories'
  id: '__root__' | '/' | '/memories' | '/memories/$id' | '/memories/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MemoriesRoute: typeof MemoriesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/memories': {
      id: '/memories'
      path: '/memories'
      fullPath: '/memories'
      preLoaderRoute: typeof MemoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memories/': {
      id: '/memories/'
      path: '/'
      fullPath: '/memories/'
      preLoaderRoute: typeof MemoriesIndexRouteImport
      parentRoute: typeof MemoriesRoute
    }
    '/memories/$id': {
      id: '/memories/$id'
      path: '/$id'
      fullPath: '/memories/$id'
      preLoaderRoute: typeof MemoriesIdRouteImport
      parentRoute: typeof MemoriesRoute
    }
  }
}

interface MemoriesRouteChildren {
  MemoriesIdRoute: typeof MemoriesIdRoute
  MemoriesIndexRoute: typeof MemoriesIndexRoute
}

const MemoriesRouteChildren: MemoriesRouteChildren = {
  MemoriesIdRoute: MemoriesIdRoute,
  MemoriesIndexRoute: MemoriesIndexRoute,
}

const MemoriesRouteWithChildren = MemoriesRoute._addFileChildren(
  MemoriesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MemoriesRoute: MemoriesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
